### ISSUE TITLE
Exception because of a missing login_settings.properties file 

### ISSUE THREAD

**Issue by wrooot** [Alameyo/flame#2]
After the last commit running Flame results in an exception, because the settings file is not present.

java.io.FileNotFoundException: C:\Users\wroot\flame\login_settings.properties (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.alameyo.flame.controllers.settings.FlameConnectionConfigurationSettings.loadProperties(FlameConnectionConfigurationSettings.kt:39)
	at org.alameyo.flame.views.login.LoginView.loadSettings(LoginView.kt:91)
	at org.alameyo.flame.views.login.LoginView.<init>(LoginView.kt:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:410)
	at tornadofx.FXKt.find$default(FX.kt:399)
	at tornadofx.App.start(App.kt:78)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$166(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$179(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wrooot** [comment]
Hey, your first bug report for Flame :1st_place_medal:
